#!/bin/zsh

yq -r '[.body[0], .body[1]] | join(" ")' graph-info.yaml | read min max

if [[ ! -z $1 ]]; then
   file=$1
fi

here=${0:a:h}
texcount -q -utf8 -sub=chapter \
         -template="{SUB?{SUM}={TITLE}\n?SUB}\n" \
         $(yq -r '."word-length-file"' graph-info.yaml) 2>/dev/null |
    awk -F= -f $here/texcount-proc.awk |
    sed 's/\\textsubscript/_/;s/&/\\&/' |
    gnuplot -p -c $here/chapter-sizes.gp $min $max $file
